version: "3"
services:
  inventory-managemant:
    build:
      context: ./
    ports:
    - 8080:8080
    environment:
      HOST: localhost
      PORT : 8080
      DBHOST : db
      DBPORT : 5432
      DBNAME : inventory_managemant
      DBUSER : postgres
      DBPASSWORD : postgres
      RMQ_URI : amqp://rabbitmq:rabbitmq@rabbitmq:5672/
      RMQ_QUEUENAME : shipment
    networks:
      - db
      - rabbitmq
networks:
  db:
    external:
      name: postgres_default
  rabbitmq:
    external:
      name: rabbitmq_default               